

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/flowable-demo?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
flowable:
  async-executor-activate: false
  process-definition-location-prefix: classpath*:/processes/
#logging:
#  level:
#    root: debug
server:
  port: 8081
